### ISSUE TITLE
Monorepo vs Multi-Package Repo Naming

### ISSUE THREAD

**Issue by mitchellhamilton** [Thinkmill/monorepo#3]
For context, a bit ago, @Noviny and I settled on using the term multi-package repo on Changesets, I've since changed Preconstruct to use the term and Manypkg used the term from the start. The reasoning behind using the term multi-package repo is that it more clearly describes what it really is. For our usages, we're describing a repo that has multiple packages, not necessarily using a single repo for an organisation or even necessarily a project.

I'm not totally sure about this though because I feel like this might be focusing too much on correctness at the expense of sharing the same terminology used widely in the community. Multi-package repo isn't used much, as a simple test, I searched for "javascript monorepo" and "javascript multi-package repo". Most of the results for both searches used the term monorepo, there were a couple usages of the term multi-package repo in a small number of blog posts and more notably on the Lerna site.

---

I'm mostly leaning towards multi-package repo with a "we're using the term multi-package repo and not monorepo because of these reasons but you'll probably hear the term monorepo in the JavaScript ecosystem and it's probably referring to multi-package repo" in the content but the thing I'm really not sure about is what the name of this repo should be because if people are searching for monorepo, we ideally want it be discoverable but maybe if we mention monorepo in the content it'll be fine?

**Comment by Noviny** [comment]
**decisions** - reach through offline discussions:

Aligning with the rest of the ecosystem is fundamentally going to be more useful. There is a discussion currently at the end of the document on `monorepo v many-package repo` that will likely be moved to be a leading piece talking about 'what is a monorepo' for the document, and references to many/multi-package are going to be converted to 'monorepo'

I'll close this ticket once I have done that.
